
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bimal
 */
public class CollegeInfo extends javax.swing.JFrame {

    /**
     * Creates new form CollegeInfo
     */
    public CollegeInfo() {
        initComponents();
        loadFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        collegeIsTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        collegeCategorySearchCB = new javax.swing.JComboBox<>();
        searchFeeTF = new javax.swing.JTextField();
        searchFeeL = new javax.swing.JLabel();
        searchByFeeB = new javax.swing.JButton();
        searchByCategoryB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        contactL = new javax.swing.JLabel();
        collegeCategoryCB = new javax.swing.JComboBox<>();
        feeTF = new javax.swing.JTextField();
        streamL = new javax.swing.JLabel();
        scholarL = new javax.swing.JLabel();
        feeL = new javax.swing.JLabel();
        catL = new javax.swing.JLabel();
        affilationCB = new javax.swing.JComboBox<>();
        idL = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        addressTA = new javax.swing.JTextArea();
        yes = new javax.swing.JRadioButton();
        addressL = new javax.swing.JLabel();
        affL = new javax.swing.JLabel();
        collegeNameTF = new javax.swing.JTextField();
        addCollegeB = new javax.swing.JButton();
        no = new javax.swing.JRadioButton();
        contactTF = new javax.swing.JTextField();
        nameL = new javax.swing.JLabel();
        itCB = new javax.swing.JCheckBox();
        bbaCB = new javax.swing.JCheckBox();
        managementCB = new javax.swing.JCheckBox();
        scienceCB = new javax.swing.JCheckBox();
        artCB = new javax.swing.JCheckBox();
        otherCB = new javax.swing.JCheckBox();
        clearB = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        openFile = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        guide = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("College Information System Interface");

        jPanel1.setBackground(new java.awt.Color(178, 194, 191));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

        collegeIsTable.setBackground(new java.awt.Color(204, 204, 204));
        collegeIsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "college ID", "College Name", "Catgegory", "Affiliation", "Stream", "Scholarship", "College fee (Rs)", "Address", "Contact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(collegeIsTable);
        if (collegeIsTable.getColumnModel().getColumnCount() > 0) {
            collegeIsTable.getColumnModel().getColumn(0).setResizable(false);
            collegeIsTable.getColumnModel().getColumn(0).setPreferredWidth(15);
            collegeIsTable.getColumnModel().getColumn(5).setResizable(false);
            collegeIsTable.getColumnModel().getColumn(5).setPreferredWidth(15);
            collegeIsTable.getColumnModel().getColumn(6).setResizable(false);
            collegeIsTable.getColumnModel().getColumn(6).setPreferredWidth(25);
            collegeIsTable.getColumnModel().getColumn(8).setResizable(false);
            collegeIsTable.getColumnModel().getColumn(8).setPreferredWidth(20);
        }

        jPanel2.setBackground(new java.awt.Color(234, 236, 229));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        collegeCategorySearchCB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        collegeCategorySearchCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Technical Institute and Professional School", "Community College", "Junior College", "Women's college", "Public College" }));

        searchFeeTF.setColumns(5);
        searchFeeTF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        searchFeeTF.setBorder(null);

        searchFeeL.setBackground(new java.awt.Color(255, 255, 255));
        searchFeeL.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        searchFeeL.setText("College Fee :");

        searchByFeeB.setBackground(new java.awt.Color(204, 204, 204));
        searchByFeeB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        searchByFeeB.setText("Search College");
        searchByFeeB.setBorder(null);
        searchByFeeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByFeeBActionPerformed(evt);
            }
        });

        searchByCategoryB.setBackground(new java.awt.Color(204, 204, 204));
        searchByCategoryB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        searchByCategoryB.setText("College available in the category");
        searchByCategoryB.setBorder(null);
        searchByCategoryB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByCategoryBActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel1.setText("Category :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(searchFeeL))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchFeeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(collegeCategorySearchCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchByFeeB, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchByCategoryB, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchFeeL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchFeeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(searchByFeeB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(collegeCategorySearchCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(searchByCategoryB, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        jPanel3.setBackground(new java.awt.Color(234, 236, 229));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        contactL.setBackground(new java.awt.Color(255, 255, 255));
        contactL.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        contactL.setText("Contact:");

        collegeCategoryCB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        collegeCategoryCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Technical Institute and Professional School", "Community College", "Junior College", "Women's college", "Public College" }));
        collegeCategoryCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collegeCategoryCBActionPerformed(evt);
            }
        });

        feeTF.setColumns(15);
        feeTF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        feeTF.setBorder(null);

        streamL.setBackground(new java.awt.Color(255, 255, 255));
        streamL.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        streamL.setText("Stream:");

        scholarL.setBackground(new java.awt.Color(255, 255, 255));
        scholarL.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        scholarL.setText("Scholarship");

        feeL.setBackground(new java.awt.Color(255, 255, 255));
        feeL.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        feeL.setText("College Fee:");

        catL.setBackground(new java.awt.Color(255, 255, 255));
        catL.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        catL.setText("Category:");

        affilationCB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        affilationCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "London Metropolitan University", "University of Wolver Hampton", "Tribhuwan University", "Pokhara University", "Kathmandu University" }));

        idL.setBackground(new java.awt.Color(255, 255, 255));
        idL.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        idL.setText("ID:");

        idTF.setColumns(15);
        idTF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        idTF.setBorder(null);

        addressTA.setColumns(20);
        addressTA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addressTA.setRows(5);
        addressTA.setBorder(null);
        jScrollPane2.setViewportView(addressTA);

        yes.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(yes);
        yes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        yes.setText("Yes");
        yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesActionPerformed(evt);
            }
        });

        addressL.setBackground(new java.awt.Color(255, 255, 255));
        addressL.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        addressL.setText("Address:");

        affL.setBackground(new java.awt.Color(255, 255, 255));
        affL.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        affL.setText("Affiliation:");

        collegeNameTF.setColumns(15);
        collegeNameTF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        collegeNameTF.setBorder(null);

        addCollegeB.setBackground(new java.awt.Color(204, 204, 204));
        addCollegeB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addCollegeB.setText("Add College");
        addCollegeB.setBorder(null);
        addCollegeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCollegeBActionPerformed(evt);
            }
        });

        buttonGroup1.add(no);
        no.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        no.setText("No");
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });

        contactTF.setColumns(15);
        contactTF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        contactTF.setBorder(null);

        nameL.setBackground(new java.awt.Color(255, 255, 255));
        nameL.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        nameL.setText("Name:");

        itCB.setText("BIT");

        bbaCB.setText("BBA");

        managementCB.setText("Management");

        scienceCB.setText("Engineering");

        artCB.setText("Arts");

        otherCB.setText("Others");

        clearB.setBackground(new java.awt.Color(204, 204, 204));
        clearB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        clearB.setText("Clear");
        clearB.setBorder(null);
        clearB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap(4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contactL, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scholarL, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addressL, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idL, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(contactTF)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(yes)
                                                .addGap(18, 18, 18)
                                                .addComponent(no))
                                            .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nameL, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(feeL)
                                            .addComponent(streamL, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jScrollPane2)
                                        .addGap(130, 130, 130))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(catL, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(affL, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(collegeCategoryCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(affilationCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(collegeNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(addCollegeB, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(feeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(clearB, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(itCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(scienceCB, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                                    .addComponent(artCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(otherCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(managementCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bbaCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(0, 36, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nameL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(collegeNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contactL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(feeL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(feeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(contactTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(scholarL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(yes)
                        .addComponent(no)
                        .addComponent(streamL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bbaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itCB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(managementCB)
                            .addComponent(scienceCB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(otherCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(artCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(affL, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(affilationCB)
                        .addComponent(addCollegeB, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clearB, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(collegeCategoryCB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(234, 236, 229));

        jLabel2.setBackground(new java.awt.Color(234, 236, 229));
        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel2.setText("College Information System");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(419, 419, 419))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel3.setText("Search College Based on");

        jLabel4.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel4.setText("Add Information");

        jPanel5.setBackground(new java.awt.Color(234, 236, 229));

        jLabel5.setBackground(new java.awt.Color(183, 215, 232));
        jLabel5.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel5.setText("College Details");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(581, 581, 581))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        file.setText("File");

        openFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        openFile.setText("Open File");
        openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileActionPerformed(evt);
            }
        });
        file.add(openFile);

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        file.add(exit);

        jMenuBar.add(file);

        help.setText("Help");

        guide.setText("Guide of whole system");
        guide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guideActionPerformed(evt);
            }
        });
        help.add(guide);

        jMenuBar.add(help);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileActionPerformed
        try{  
            //constructor of file class having file as argument                                           
            File file = new File("CollegeIS.txt");
            if(!Desktop.isDesktopSupported())//check if Desktop is supported by Platform or not  
            {  
            System.out.println("not supported");  
            return;  
            }  
            Desktop desktop = Desktop.getDesktop();  
            if(file.exists()){
                desktop.open(file);
                System.out.println("File opened.");
            }
            else{
                System.out.println("File not present.");
            }
        } catch(Exception e) {  
            e.printStackTrace();  
        } 
    }//GEN-LAST:event_openFileActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed
   
    private void guideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guideActionPerformed
        new HelpFrame().setVisible(true);
    }//GEN-LAST:event_guideActionPerformed

    private void searchByFeeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByFeeBActionPerformed
       //validation for search fee text
        int target = 0;
        if(searchFeeTF.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Please! Enter fee details to search College.");
            return;
        }
        try{
            target = Integer.parseInt(searchFeeTF.getText());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Invalid fee inserted.");
            return;
        }
        
        // Get sorted feeList.
        int[] fee = new int[collegeIsTable.getRowCount()];
        for (int row = 0; row < collegeIsTable.getRowCount(); row++){
            fee[row] = Integer.parseInt(collegeIsTable.getValueAt(row, 6).toString());
        }
        sort(fee);
        
        
        int result = binSearch(fee, target);
        if(result == -1){
            JOptionPane.showMessageDialog(rootPane, "The college with given fee is not present in the College Information System."); 
        }
        else{
            for(int row = 0; row<collegeIsTable.getRowCount(); row++) {
                if(fee[result] == Integer.parseInt(collegeIsTable.getValueAt(row, 6).toString())) {
                    JOptionPane.showMessageDialog(rootPane, "The details of college with fee \"" +target+"\" is given below: "+ "\n\nCollege ID : " +  collegeIsTable.getValueAt(row, 0) + "\nCollege Name: " + collegeIsTable.getValueAt(row, 1)+ "\nCategory: " + collegeIsTable.getValueAt(row, 2) + "\nAffiliation: "+ collegeIsTable.getValueAt(row, 3)+ "\nStream: " + collegeIsTable.getValueAt(row, 4)+ "\nScholarship: "+ collegeIsTable.getValueAt(row, 5)+ "\nCollege Fee: Rs. " + collegeIsTable.getValueAt(row, 6) + "\nAddress: " + collegeIsTable.getValueAt(row, 7) + "\nContact: " + collegeIsTable.getValueAt(row, 8));
                    break;
                }
            }
        }
        searchFeeTF.setText("");
    }//GEN-LAST:event_searchByFeeBActionPerformed

    private void searchByCategoryBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByCategoryBActionPerformed
        String target = collegeCategorySearchCB.getSelectedItem().toString();
        int count = 0;
        String college = "";
        for(int row = 0; row < collegeIsTable.getRowCount(); row++) {
            if(collegeIsTable.getValueAt(row, 2).toString().equals(target)) {
                count = count + 1;
                college = college + ((count) + ". " + collegeIsTable.getValueAt(row, 1).toString() + "\n");
            }
        }
        
        if(count == 0) {
            JOptionPane.showMessageDialog(rootPane, "There are no colleges with Category \"" + target + "\"");    
        } else {
            JOptionPane.showMessageDialog(rootPane, " There are "+ count+" colleges with Category \"" + target + "\" which are: \n"+ college);
        }
    }//GEN-LAST:event_searchByCategoryBActionPerformed

    private void addCollegeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCollegeBActionPerformed
        if(isFormValid()){
            //get either scholarship is provided or not.
            String scholarship;
            if(yes.isSelected()){
                scholarship = yes.getText();
            }
            else{
                 scholarship = no.getText();
            }
            
            //get stream details.
            String stream = "";
            if(scienceCB.isSelected()) stream = stream+ scienceCB.getText()+ " / ";
            if(managementCB.isSelected()) stream = stream+ managementCB.getText()+ " / ";
            if(artCB.isSelected()) stream = stream+ artCB.getText()+ " / ";
            if(itCB.isSelected()) stream = stream+ itCB.getText()+ " / ";
            if(bbaCB.isSelected()) stream = stream+ bbaCB.getText()+ " / ";
            if(otherCB.isSelected()) stream = stream+ otherCB.getText()+ " / ";
            stream = stream.substring(0, stream.length() - 3); 

            String [] list = {idTF.getText(), collegeNameTF.getText(), collegeCategoryCB.getSelectedItem().toString(), affilationCB.getSelectedItem().toString(), stream, scholarship, feeTF.getText(), addressTA.getText(),contactTF.getText()};
            DefaultTableModel table = (DefaultTableModel) collegeIsTable.getModel();
            table.addRow(list);
            try {
                File file = new File("CollegeIS.txt");
                // create file if not exists
                if(!file.exists()) {
                    file.createNewFile();
                    System.out.println("File Created");
                }
                FileWriter fileWriter = new FileWriter(file,true);
                // initialize BufferedWriter

                BufferedWriter writer = new BufferedWriter(fileWriter);
                for(int i = 0; i< list.length; i++) {
                    writer.write(list[i]);
                    if(i != list.length-1){
                        writer.write(",   ");
                    }
                }
                writer.newLine();
                writer.close();
                fileWriter.close();
            } catch (Exception e) {
                e.printStackTrace();
                System.out.println("Exception is shown while writing information into txt file part.");
            }

            JOptionPane.showMessageDialog(rootPane, "College details added to the College Information System.");
            //clear all the field.
            clearText();
        }
    }//GEN-LAST:event_addCollegeBActionPerformed

    private void yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed

    private void collegeCategoryCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collegeCategoryCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collegeCategoryCBActionPerformed

    private void clearBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBActionPerformed
        clearText();
    }//GEN-LAST:event_clearBActionPerformed

    private boolean isFormValid(){
        if(idTF.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Please! fill up College id in the form to save information.");
            return false;
        }
        else if(collegeNameTF.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Please! fill up College Name in the form to save information.");
            return false;
        }
        else if(collegeCategoryCB.getSelectedItem().toString().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Please! select college category in the form to save information.");
            return false;
        }
        else if(affilationCB.getSelectedItem().toString().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Please! select affilation option in the form to save information.");
            return false;
        }
        else if(buttonGroup1.isSelected(null)){
            JOptionPane.showMessageDialog(rootPane, "Please! select either yes or no for scholarship field in the form to save information.");
            return false;
        }
        else if(feeTF.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Please! fill up College fee in the form to save information.");
            return false;
        }
        
        else if(addressTA.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Please! fill up College address in the form to save information.");
            return false;
        }
        else if(contactTF.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Please! fill up College contact in the form to save information.");
            return false;
        }
        
        if(!(scienceCB.isSelected() || managementCB.isSelected() || artCB.isSelected() || itCB.isSelected() || bbaCB.isSelected() || otherCB.isSelected())){
            JOptionPane.showMessageDialog(rootPane, "Please! select stream option in the form to save information.");
            return false;
        }
        
        if(!(idTF.getText().isEmpty())){
            for (int row = 0; row < collegeIsTable.getRowCount(); row++){
                if(collegeIsTable.getValueAt(row, 0).toString().equals(idTF.getText())){
                    JOptionPane.showMessageDialog(rootPane, "The college with given College ID is already present in the Information System. \nPlease! Insert another College ID to insert details.");  
                    return false;
                }
            }
        }
        
        
        if(!(feeTF.getText().isEmpty())){
            try{
                Integer.parseInt(feeTF.getText());
            }
            catch(NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Invalid Fee!! \nPlease! Enter the Fee in number format.");
                return false;
            }
        }
        
        return true;
    }
    
    private void clearText(){
        idTF.setText("");
        collegeNameTF.setText("");
        collegeCategoryCB.setSelectedItem("");
        affilationCB.setSelectedItem("");
        scienceCB.setSelected(false);
        managementCB.setSelected(false);
        artCB.setSelected(false);
        itCB.setSelected(false);
        bbaCB.setSelected(false);
        otherCB.setSelected(false);
        buttonGroup1.clearSelection();
        feeTF.setText("");
        addressTA.setText("");
        contactTF.setText("");
    }
    // this will load all the details of .txt file to table.
    private void loadFile(){
        try {
            File file = new File("CollegeIS.txt");
            FileReader fileReader = new FileReader(file);
            BufferedReader bufferedReader = new BufferedReader(fileReader);
            String line = bufferedReader.readLine();
            
            while(line != null) {
                DefaultTableModel table = (DefaultTableModel) collegeIsTable.getModel();
                String row[] = line.split(",   ");
                table.addRow(row);
                line = bufferedReader.readLine();
            }
            
        } catch (IOException ioe) {
            System.out.println("File is not created yet.");
        }
    }
     
    // Get sorted feeList to be used in binary search.
    public int[] sort(int[]a){
        for(int i = 0; i< a.length-1 ; i++ ){
            int minPos = minimumPosition(a, i);
            swap(a, minPos, i);
        }
        return a;
    }
    private int minimumPosition(int[] a, int from){
        int minPos = from;
        for(int j = from + 1; j < a.length; j++){
            if (a[j]< a[minPos]){
                minPos = j;
            }
        }
        return minPos;
    }
    private void swap(int[] a, int i, int j){
        int temp = a[i];
        a[i] = a[j];
        a[j] = temp;
    }
    
    // this is binarySearch method for listing colleges according to fee
    public int binSearch(int[] list, int target){
        int lowPosn = 0;
        int highPosn = list.length -1;
        while(lowPosn <= highPosn){
            int midPosn = (lowPosn + highPosn)/2;
            if(list[midPosn] == target){
                return midPosn;
            }
            else if(list[midPosn] > target){
                highPosn = midPosn -1;
            }
            else{
                lowPosn = midPosn +1;
            }
        }
        
        return -1;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CollegeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CollegeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CollegeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CollegeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CollegeInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCollegeB;
    private javax.swing.JLabel addressL;
    private javax.swing.JTextArea addressTA;
    private javax.swing.JLabel affL;
    private javax.swing.JComboBox<String> affilationCB;
    private javax.swing.JCheckBox artCB;
    private javax.swing.JCheckBox bbaCB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel catL;
    private javax.swing.JButton clearB;
    private javax.swing.JComboBox<String> collegeCategoryCB;
    private javax.swing.JComboBox<String> collegeCategorySearchCB;
    private javax.swing.JTable collegeIsTable;
    private javax.swing.JTextField collegeNameTF;
    private javax.swing.JLabel contactL;
    private javax.swing.JTextField contactTF;
    private javax.swing.JMenuItem exit;
    private javax.swing.JLabel feeL;
    private javax.swing.JTextField feeTF;
    private javax.swing.JMenu file;
    private javax.swing.JMenuItem guide;
    private javax.swing.JMenu help;
    private javax.swing.JLabel idL;
    private javax.swing.JTextField idTF;
    private javax.swing.JCheckBox itCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox managementCB;
    private javax.swing.JLabel nameL;
    private javax.swing.JRadioButton no;
    private javax.swing.JMenuItem openFile;
    private javax.swing.JCheckBox otherCB;
    private javax.swing.JLabel scholarL;
    private javax.swing.JCheckBox scienceCB;
    private javax.swing.JButton searchByCategoryB;
    private javax.swing.JButton searchByFeeB;
    private javax.swing.JLabel searchFeeL;
    private javax.swing.JTextField searchFeeTF;
    private javax.swing.JLabel streamL;
    private javax.swing.JRadioButton yes;
    // End of variables declaration//GEN-END:variables
}
